name: toannm_test
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: 2.2.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  dio: 4.0.0 # http client
  get: 4.3.4

  pull_to_refresh: 2.0.0
  cached_network_image: 3.1.0

  get_storage: 2.0.3

  mockito: 5.0.14
  http: ^0.13.3
  build_runner: ^2.1.0

  intl: ^0.17.0

  diacritic: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/json/
    - assets/icons/
